# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "changes", :force => true do |t|
    t.column "changeset_id", :integer
    t.column "revision", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 2, :default => "", :null => false
    t.column "path", :text, :default => "", :null => false
    t.column "from_path", :text
    t.column "from_revision", :integer
  end

  create_table "changesets", :force => true do |t|
    t.column "revision", :integer
    t.column "author", :string, :limit => 50
    t.column "log", :text
    t.column "created_at", :datetime
    t.column "revised_at", :datetime
  end

  create_table "milestones", :force => true do |t|
    t.column "name", :string, :limit => 75
    t.column "info", :text
    t.column "due", :date
    t.column "completed", :integer, :default => 0
    t.column "created_at", :datetime
  end

  create_table "parts", :force => true do |t|
    t.column "name", :string, :limit => 50
  end

  create_table "releases", :force => true do |t|
    t.column "name", :string, :limit => 25
  end

  create_table "sessions", :force => true do |t|
    t.column "sessid", :string, :limit => 32
    t.column "data", :text
  end

  create_table "severities", :force => true do |t|
    t.column "position", :integer
    t.column "name", :string, :limit => 50
  end

  create_table "status", :force => true do |t|
    t.column "name", :string, :limit => 25
  end

  create_table "ticket_changes", :force => true do |t|
    t.column "ticket_id", :integer
    t.column "author", :string, :limit => 75
    t.column "comment", :text
    t.column "created_at", :datetime
    t.column "log", :text
    t.column "attachment", :string
    t.column "content_type", :string, :limit => 100
    t.column "attachment_fsname", :string
  end

  create_table "tickets", :force => true do |t|
    t.column "milestone_id", :integer, :default => 0
    t.column "part_id", :integer, :default => 0
    t.column "severity_id", :integer, :default => 0, :null => false
    t.column "release_id", :integer
    t.column "status_id", :integer, :default => 1, :null => false
    t.column "author", :string, :limit => 75
    t.column "summary", :string
    t.column "content", :text
    t.column "author_host", :string, :limit => 100
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80
    t.column "password", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "view_changesets", :boolean, :default => true
    t.column "view_code", :boolean, :default => true
    t.column "view_tickets", :boolean, :default => true
    t.column "create_tickets", :boolean, :default => true
    t.column "admin", :boolean, :default => false
    t.column "view_milestones", :boolean, :default => true
  end

end
